version: '3.6'
services:
  web:
    image: php:8.1-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=America/Sao_Paulo

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes_from:
      - web
    command: install

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./mariadb:/usr/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo
  
  php_admin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
  